# Generated by Django 4.2.4 on 2023-08-08 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("profissao", models.CharField(max_length=50)),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("F", "Feminino"),
                            ("M", "Masculino"),
                            ("N", "Nenhuma das opções"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=200)),
                ("numero", models.IntegerField()),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("bairro", models.CharField(max_length=50)),
                ("cidade", models.CharField(max_length=100)),
                ("pais", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Entregador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                (
                    "turno",
                    models.CharField(
                        choices=[("M", "Manha"), ("T", "Tarde"), ("N", "Noite")],
                        max_length=1,
                    ),
                ),
                ("cpf", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observacoes", models.CharField(max_length=300)),
                ("data_pedido", models.DateTimeField()),
                ("valor", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pedido realizado"),
                            ("F", "Fazendo"),
                            ("E", "Saiu para entrega"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="application.cliente",
                    ),
                ),
                (
                    "entregador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregadores",
                        to="application.entregador",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cliente",
            name="endereco",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="application.endereco",
            ),
        ),
    ]
