# Generated by Django 4.2.4 on 2023-08-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entregador",
            name="turno",
            field=models.CharField(
                choices=[("M", "Manhã"), ("T", "Tarde"), ("N", "Noite")], max_length=1
            ),
        ),
    ]
